### ISSUE TITLE
Model training for classification

### ISSUE THREAD

**Issue by akash-cs13** [akash-cs13/MSE_Sem2#8]
Train a machine-learning model for classifying STOP and PRIORITY signs using the dataset in data.zip. Make use of Google Colab and train with Resnet18 and MobilenetV3

**Comment by akash-cs13** [comment]
The training is stopped at 8/24 epochs and .pth files and model evaluation is pending

**Comment by kanika-sehgal123** [comment]
It has not stopped there. Link to Google collab is also shared and it was complete

**Comment by kanika-sehgal123** [comment]
I'll upload again
